name: app

type: php:8.0

runtime:
    extensions:
        - apcu
        - amqp
        - mbstring
        - sodium
        - ctype
        - iconv
        

#variables:
#    php:
#        # uncomment on PHP 7.4+
#        #opcache.preload: /app/config/preload.php

build:
    flavor: none

disk: 512

relationships:
    database: "db:postgresql"
    redis: "rediscache:redis"
    rabbitmq: "queue:rabbitmq"

web:
    locations:
        "/":
            root: "public"
            expires: 1h
            passthru: "/index.php"



mounts:
    "/var": { source: local, source_path: var }
    "/public/uploads": { source: local, source_path: uploads }

hooks:
    build: |
        set -x -e

        curl -fs https://get.symfony.com/cloud/configurator | (>&2 bash)
        
        (>&2 symfony-build)

    deploy: |
        set -x -e

        (>&2 symfony-deploy)
